### ISSUE TITLE
首页的自定义滚动文章背景取色问题

### ISSUE THREAD

**Issue by PG-Z** [michaelliunsky/niRvana-theme#32]
最近几个版本都没有取对于图片的主色了。

**Comment by michaelliunsky** [comment]
你好，我无法复现，希望提供网站地址。

**Comment by yonglinzhu** [comment]
我访问你的网站就没变色啊。

![image](https://github.com/michaelliunsky/niRvana-theme/assets/26948420/586b49e1-f097-4875-ab64-7845902e13d8)

**Comment by PG-Z** [comment]
回退了好几个版本，到v5.0.0-beta10正常了。

**Comment by michaelliunsky** [comment]
抱歉，知道了，周末有空再看看

**Comment by michaelliunsky** [comment]
现在确认了一下，在**BETA12没有问题**，BETA13及之后版本出了问题

**Comment by michaelliunsky** [comment]
查了好久错误，结果发现是一行代码出了错![image](https://github.com/michaelliunsky/niRvana-theme/assets/103762450/fde38a85-10ac-4992-bbdb-0501fe3f9a0a)

**Comment by michaelliunsky** [comment]
我**已经发布了RC2版本，修复了错误**，请你们看看还**有无问题**？ @yonglinzhu @PG-Z

**Comment by yonglinzhu** [comment]
> 我**已经发布了RC2版本，修复了错误**，请你们看看还**有无问题**？ @yonglinzhu @PG-Z

已更新，没问题。感谢辛苦维护❤️❤️❤️
