### ISSUE TITLE
输入框变形无法输入

### ISSUE THREAD

**Issue by onepve** [michaelliunsky/niRvana-theme#34]
```
nginx	nginx
MySQL	8.2.0（最低要求：5.5.5）
PHP	8.3.8（最低要求：7.0.0）
Zend	4.3.8
WordPress	6.5.5（57155）
TinyMCE	49110-20201110
```
感谢作者更新主题.真是好看.就是应用后输入框被遮罩了..没发输入内容....

![0aa987e2-e5b5-43ae-bf3e-9f887aba7d79](https://github.com/user-attachments/assets/3f14fdb7-32d5-4e93-a8be-188539923e7e)
![be5a7165-771a-4e44-8a3d-05fbd95f2f12](https://github.com/user-attachments/assets/dde40a07-9742-4285-9c84-fb786b006db0)
![934b9e8d-cdf3-47cd-ba0a-05a6dbc575e0](https://github.com/user-attachments/assets/48f1eb14-0661-406e-a48e-1118f26806ec)

**Comment by michaelliunsky** [comment]
在**Wordpress 6.6**下测试，使用**PHP 8.3.7**版本，一切正常。可能是你浏览器问题，这边使用**Safari**没问题。
<img width="1199" alt="截屏2024-07-21 13 40 22" src="https://github.com/user-attachments/assets/51db699b-4789-4d21-b709-13e37818d489">
<img width="1234" alt="截屏2024-07-21 13 40 57" src="https://github.com/user-attachments/assets/23cb6a89-8fe5-4465-94c2-8402bea7dffb">
